auto: true

markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title

title: Zhiyuan's Blog
url: https://zhiyuanliplus.github.io
feed: /atom.xml
author_info: <a href="https://zhiyuanliplus.github.io/">Zhiyuan's Blog</a>
